### PR TITLE
Bump version express 4.18.2 -> 4.21.0.

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes # .

Changes proposed in this PR:

- 
- 
-

### CODE REVIEW

**Comment by mariacarmina** [comment]
Unit test failing -> `Segmentation fault (core dumped)`

**Comment by jamiehewitt15** [comment]
> Unit test failing -> `Segmentation fault (core dumped)`

Do we know what the issue is that's causing this?

**Review by paulo-ocean — APPROVED** [review]

**Comment by paulo-ocean** [comment]
> > Unit test failing -> `Segmentation fault (core dumped)`
> 
> Do we know what the issue is that's causing this?

I believe its the Blockchain / RPC connection retry mechanism (when we have wrong/invalid RPCs... it can't get a proper connection and keeps recursively retrying forever... doing a `new JSONRPCProvider()` call .. It kills the memory
This is already addressed on the Elastic search PR ... since that part was refactored (it tries to reconnect 10 X at most)

**Review by jamiehewitt15 — APPROVED** [review]
Looks good to me

**Pull request merged**
