### PR TITLE
Remove private keys from tests

### LINKED ISSUE #402: Remove explicit private keys in the code and getSigner(0) from account creation in tests
Use blockchain class signer instead of getSigner(0) -> does not work for other networks.

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes #402  .

Changes proposed in this PR:

- 
- 
-

### CODE REVIEW

**Comment by jamiehewitt15** [comment]
Are you still working on this?

**Comment by mariacarmina** [comment]
> Are you still working on this?

Yes, but it is low prio, have some other PRs with higher prio to fix, I'll get back to it.

**Comment by mihaisc** [comment]
@mariacarmina status on this?

**Comment by mariacarmina** [comment]
This issue is still up, but need to start from main branch now. Closing it now.

**Pull request closed without merging**
