### PR TITLE
test multiplatform build

### LINKED ISSUE #76: Add ARM support

### PR DESCRIPTION
**Pull request by alexcos20**
Closes #76

image

### CODE REVIEW

**Review by jamiehewitt15 — APPROVED** [review]
Looks good to me

**Review by bogdanfazakas — APPROVED** [review]
lgtm, not sure if worth trying the images from docker hub on some arm machines

**Review by paulo-ocean — APPROVED** [review]
LGTM. i could build it on a mac

**Comment by mariacarmina** [comment]
Let's merge the latest changes in this branch, too.

**Pull request merged**
