### PR TITLE
Fix/ integration test regarding ddo state 

### LINKED ISSUE #388: There is a failing integration test regarding ddo state
After the changes done for "state ddo" database, we have a test that  fails
"`should store the ddo state in the db with no errors and retrieve it using did`"
there is something wrong there, maybe a timeout or something, might worth a look

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes #388  .

Changes proposed in this PR:

- 
- 
-

### CODE REVIEW

**Comment by bogdanfazakas** [comment]
think we can close this @paulo-ocean , was something off with barge as it seems, cause all was green locally and same in the branch i ve merge , also now green on main 🤯

**Comment by paulo-ocean** [comment]
> think we can close this @paulo-ocean , was something off with barge as it seems, cause all was green locally and same in the branch i ve merge , also now green on develop after a re-run 🤯

Are you sure @bogdanfazakas ? cause it keeps failing on other branches even after a re-run.. its a bit strange that only one and the same test would be affected by barge... 
i think it might be some random thing instead

**Comment by paulo-ocean** [comment]
this is definitely no ok, there is a bug somewhere, the same test keeps failing randomly , in multiple branches

**Comment by bogdanfazakas** [comment]
> this is definitely no ok, there is a bug somewhere, the same test keeps failing randomly , in multiple branches

yes there is an issue with an asset beeing  already active from time to time when just published, investigating that

**Comment by paulo-ocean** [comment]
> > this is definitely no ok, there is a bug somewhere, the same test keeps failing randomly , in multiple branches
> 
> yes there is an issue with an asset being already active from time to time when just published, think something related to things that got shared beetween test files investigating that

yeah, i suspect something similar, we are using the sample example DDOs in many places

**Comment by bogdanfazakas** [comment]
> > > this is definitely no ok, there is a bug somewhere, the same test keeps failing randomly , in multiple branches
> > 
> > 
> > yes there is an issue with an asset being already active from time to time when just published, think something related to things that got shared beetween test files investigating that
> 
> yeah, i suspect something similar, we are using the sample example DDOs in many places

think i found it, let me test it more, maybe related to indexer loop

**Comment by bogdanfazakas** [comment]
closing this, fixed in #360

**Pull request closed without merging**
