### PR TITLE
Improve logs download: adding query parameters

### PR DESCRIPTION
**Pull request by tom1145**
Fixes [#320](https://github.com/oceanprotocol/ocean-node/issues/320).

Changes proposed in this PR:

- adds filter inputs for downloading the logs

### CODE REVIEW

**Comment by jamiehewitt15** [comment]
Can you pull the latest changes from origin develop to fix the issue with the test?

**Comment by tom1145** [comment]
> Can you pull the latest changes from origin develop to fix the issue with the test?

I made a sync on both of them now. Thanks!

**Review by jamiehewitt15 — APPROVED** [review]
I made some changes to make sure this works with the new authentication that's required to download the logs + updated the styling. Now using MUI as a simple way to improve the UX. 

image

**Review by paulo-ocean — APPROVED** [review]
lgtm

**Comment by bogdanfazakas** [comment]
Hey @jamiehewitt15  is download logs functionality working on your end? i always end up with a 403 with invalid signature error.
Screenshot 2024-05-08 at 08 22 06
Screenshot 2024-05-08 at 08 23 25

**Comment by jamiehewitt15** [comment]
Thanks for testing this @bogdanfazakas. The expiry timestamp in your request is `1713301201844` = `Tuesday, 16 April 2024` so it's already expired. It should ask you for another signature in this situation, so I'll look into why that's not happening.

**Comment by jamiehewitt15** [comment]
@bogdanfazakas I've introduced some improvements that should solve your issue: 

1. signature and expiry timestamp are only stored in local storage if they are still valid
2. they are only used, when retrieved from local storage if they are still valid
3. if the signature is from a different account to the one currently connected, they are removed.
4. Better error responses on the auth function. 

Could you test it again from the same browser? It should recognise that your expiryTimestamp is in the past and show you the unlock button so that you sign another message.

**Comment by bogdanfazakas** [comment]
> @bogdanfazakas I've introduced some improvements that should solve your issue:
> 
> 1. signature and expiry timestamp are only stored in local storage if they are still valid
> 2. they are only used, when retrieved from local storage if they are still valid
> 3. if the signature is from a different account to the one currently connected, they are removed.
> 4. Better error responses on the auth function.
> 
> Could you test it again from the same browser? It should recognise that your expiryTimestamp is in the past and show you the unlock button so that you sign another message.

Nice fix, immediately asked me to unlock the admin features with that came the sign again operation, then download logs worked fine. 👍

**Review by bogdanfazakas — APPROVED** [review]

**Comment by jamiehewitt15** [comment]
> Nice fix, immediately asked me to unlock the admin features with that came the sign again operation, then download logs worked fine. 👍

Excellent, thanks for testing

**Pull request merged**
