### PR TITLE
have bootstrap config var

### LINKED ISSUE #781: remove handle of commands from bootstrap nodes
disable `handleProtocolCommands`
if bootstrap node (requires new env var)

### PR DESCRIPTION
**Pull request by paulo-ocean**
Fixes #781 

Changes proposed in this PR:

- disables handling of commands if is configured as bootstrap node
- 
-

### CODE REVIEW

**Review by jamiehewitt15 — COMMENTED** [review]
Ideally it should also be added to `docs/env.md`

**Comment by paulo-ocean** [comment]
> Ideally it should also be added to `docs/env.md`

of course, just wanted to get this out asap :-)

**Review by jamiehewitt15 — APPROVED** [review]
Looks good to me. Let's not forget to add this to the docs as well

**Comment by paulo-ocean** [comment]
> Looks good to me. Let's not forget to add this to the docs as well

1 min

**Pull request merged**
