### PR TITLE
C2d docker some fixes

### PR DESCRIPTION
**Pull request by FilipMasar**
Changes proposed in this PR:

- increase maxJobDuration - 30 seconds was not enough when I run it in debugger
- ensure the image pull completion
- fix entrypoint when creating container

### CODE REVIEW

**Review by paulo-ocean — COMMENTED** [review]
just a couple of questions, by curiosity... 
why are we opening  a PR on another draft PR in progress? :-)
Why this?
`containerInfo.Entrypoint = newEntrypoint.split(' ')` (have we tested the change? Are we sure it works the same?)

Why the 10 minutes for the free compute? Isn't that too much ? Afaik, the initial idea was 30 secs
tkx

**Comment by jamiehewitt15** [comment]
> why are we opening a PR on another draft PR in progress? :-)

Yeah, I agree... We need to first focus on getting the initial PR merged before improving on it in different branches. @FilipMasar I would suggest that you leave comments and suggestions on https://github.com/oceanprotocol/ocean-node/pull/705

**Comment by alexcos20** [comment]
> why are we opening a PR on another draft PR in progress? :-)
Because this is nowhere near a Ready PR.   The compute flow was not working until two days ago, and getResults ended with uncaught exception in node.

As regarding security, we have no tests yet

**Review by alexcos20 — APPROVED** [review]
lgtm.

Regarding `maxJobDuration`, we can leave it 10 mins as long as this is a draft PR.

For production, I think we will have an env var

**Comment by alexcos20** [comment]
> Regarding this containerInfo.Entrypoint = newEntrypoint.split(' ') - without split(' ') it was not working for me. In the docs they say that exec form is preferred

What version of Docker are you running?

**Comment by paulo-ocean** [comment]
> > why are we opening a PR on another draft PR in progress? :-)
> 
> Because this is nowhere near a Ready PR. The compute flow was not working until two days ago, and getResults ended with uncaught exception in node.
> 
> As regarding security, we have no tests yet

fair enough, its still draft but we're overlapping work here

**Comment by paulo-ocean** [comment]
> Hey @paulo-ocean @jamiehewitt15 , thanks for your comments. I spoke with @alex-ocean23 that I was testing this branch, found some issues and he told me that I can open PR. Let me know if something else works better for you. Sometimes its easier to propose a fix than to explain the issue. Feel free to close this PR.
> 
> 10 minutes - because when I run it with debugger it already timeouted before I got to running algorithm flow. So probably unnecessary change - just for testing. Is this free compute intended to be available in production?
> 
> Regarding this `containerInfo.Entrypoint = newEntrypoint.split(' ')` - without split(' ') it was not working for me. In the docs they say that exec form is preferred
> 
> * https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
> * https://docs.docker.com/reference/dockerfile/#entrypoint

Ok, but it was working for me

**Comment by paulo-ocean** [comment]
> > Hey @paulo-ocean @jamiehewitt15 , thanks for your comments. I spoke with @alex-ocean23 that I was testing this branch, found some issues and he told me that I can open PR. Let me know if something else works better for you. Sometimes its easier to propose a fix than to explain the issue. Feel free to close this PR.
> > 10 minutes - because when I run it with debugger it already timeouted before I got to running algorithm flow. So probably unnecessary change - just for testing. Is this free compute intended to be available in production?
> > Regarding this `containerInfo.Entrypoint = newEntrypoint.split(' ')` - without split(' ') it was not working for me. In the docs they say that exec form is preferred
> > 
> > * https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
> > * https://docs.docker.com/reference/dockerfile/#entrypoint
> 
> Ok, but it was working for me

@FilipMasar feel free to merge the PR then
btw, i'm curious.. why do we need this syntax?
`await new Promise((resolve, reject) => {`

**Comment by paulo-ocean** [comment]
> lgtm.
> 
> Regarding `maxJobDuration`, we can leave it 10 mins as long as this is a draft PR.
> 
> For production, I think we will have an env var

@alexcos20 @FilipMasar The `maxJobDuration` is already part of the configuration, 30 seconds is just the default value if nothing else is specified. Now the default is 10 minutes

**Comment by jamiehewitt15** [comment]
> Because this is nowhere near a Ready PR. 

@alexcos20 ok yeah, that's fair enough. Let's just make sure that we don't have the same issues fixed in two different PRs

**Comment by paulo-ocean** [comment]
ok, i'm gonna merge the PR. I do have some doubts about some of thh changes made here, specially the entrypoint, since we removed the `containerId` from the path , and that was the only way it worked for me on Linux

**Comment by FilipMasar** [comment]
> > Regarding this containerInfo.Entrypoint = newEntrypoint.split(' ') - without split(' ') it was not working for me. In the docs they say that exec form is preferred
> 
> What version of Docker are you running?

Hey, sorry for late response
docker - `v27.3.1`
docker desktop - `4.35.1`

**Comment by FilipMasar** [comment]
> > > Hey @paulo-ocean @jamiehewitt15 , thanks for your comments. I spoke with @alex-ocean23 that I was testing this branch, found some issues and he told me that I can open PR. Let me know if something else works better for you. Sometimes its easier to propose a fix than to explain the issue. Feel free to close this PR.
> > > 10 minutes - because when I run it with debugger it already timeouted before I got to running algorithm flow. So probably unnecessary change - just for testing. Is this free compute intended to be available in production?
> > > Regarding this `containerInfo.Entrypoint = newEntrypoint.split(' ')` - without split(' ') it was not working for me. In the docs they say that exec form is preferred
> > > 
> > > * https://docs.docker.com/reference/dockerfile/#shell-and-exec-form
> > > * https://docs.docker.com/reference/dockerfile/#entrypoint
> > 
> > 
> > Ok, but it was working for me
> 
> @FilipMasar feel free to merge the PR then btw, i'm curious.. why do we need this syntax? `await new Promise((resolve, reject) => {`

The `followProgress` method uses a callback-based approach to handle the progress of the pull operation. To use it with await, it needs to be wrapped in a Promise

**Pull request merged**
