### PR TITLE
Check for timeout

### LINKED ISSUE #581: Ensure that we send a 408 if the express request has timed out
Ensure that we send a 408 if the express request has timed out

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #581 

Changes proposed in this PR:

- Check for timeout in express request.
- Logging the timeout
- Sending `408`

### CODE REVIEW

**Comment by paulo-ocean** [comment]
i think we might need a bigger timeout... when we're dealing with database or remote P2P nodes... depending on the request, this might not be enough.. For instance, just for the P2P connection (from node A to B) we have default timeout of 10 secs... i would double it

**Review by paulo-ocean — COMMENTED** [review]
what happens if we are streaming a response, somewhere on our handlers, and we hit this timeout?
15 seconds is way too low.. the default is 2 minutes... we're reducing way too much 
I doubt we can fulfill  any big request, specially if it deals with DB and remote peers in this interval
That said, what's the point / advantage of having a smaller request timeout?
If we have (possibly) timeout issues with bigger intervals, doesn't this change make it worst?
thanks

**Comment by jamiehewitt15** [comment]
Yeah, good to have it with a high default (2min or more) and then the option to decrease it with an env

**Comment by mihaisc** [comment]
@jamiehewitt15  status on this?

**Pull request closed without merging**
