### PR TITLE
PR for Command: getDDO

### PR DESCRIPTION
**Pull request by an7e**
Issue #49 

Changes proposed in this PR:

- added command getDDO
- added ddo handler
- added `this` context to work in methods

### CODE REVIEW

**Review by mariacarmina — COMMENTED** [review]
Looks good from my side. One question though:
Does this PR also depend on #116 for finding the DDO first and then using this PR to serve it? Should we wait for #116 or it can be merged separately?
One mention is that please merge the `develop` branch in `command-getddo`.

**Comment by alexcos20** [comment]
can you rename the PR please? :)

**Review by alexcos20 — APPROVED** [review]
lgtm, although it would be nice to have some tests

**Review by paulo-ocean — APPROVED** [review]
green light! :+1:

**Pull request merged**
